export type Tool = {
  slug: string
  name: string
  description: string
  category: string
  keywords: string[]
  page: () => Promise<{ default: any }>
  title: string
  descriptionMeta: string
  explainTitle: string
  explain: any
}

export const tools: Tool[] = [
  {
    slug: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Beautify, minify, and sort keys in JSON.',
    category: 'json',
    keywords: ['json', 'formatter', 'beautify', 'minify'],
    page: () => import('../pages/JsonTool').then((m) => ({ default: m.JsonTool })),
    title: 'JSON Formatter',
    descriptionMeta: 'Beautify and indent JSON locally in your browser — nothing is uploaded.',
    explainTitle: 'Why format JSON?',
    explain: null,
  },
  {
    slug: 'json-validator',
    name: 'JSON Validator',
    description: 'Check whether text is valid JSON and see the exact parser error.',
    category: 'json',
    keywords: ['json', 'validator', 'parse', 'error'],
    page: () => import('../pages/JsonTool').then((m) => ({ default: m.JsonTool })),
    title: 'JSON Validator',
    descriptionMeta: 'Check whether text is valid JSON, with the parser error if it isn\'t.',
    explainTitle: 'Common JSON mistakes',
    explain: null,
  },
  {
    slug: 'json-diff',
    name: 'JSON Diff',
    description: 'Compare two JSON documents line by line.',
    category: 'json',
    keywords: ['json', 'diff', 'compare'],
    page: () => import('../pages/JsonTool').then((m) => ({ default: m.JsonTool })),
    title: 'JSON Diff',
    descriptionMeta: 'Compare two JSON documents and see line-by-line additions and removals.',
    explainTitle: 'How this diff works',
    explain: null,
  },
  {
    slug: 'yaml-validator',
    name: 'YAML Validator',
    description: 'Check whether text is valid YAML and see the exact parser error.',
    category: 'yaml',
    keywords: ['yaml', 'validator', 'parse', 'error'],
    page: () => import('../pages/YamlTool').then((m) => ({ default: m.YamlTool })),
    title: 'YAML Validator',
    descriptionMeta: 'Check whether text is valid YAML, with the parser error if it isn\'t.',
    explainTitle: 'Common YAML mistakes',
    explain: null,
  },
  {
    slug: 'yaml-to-json',
    name: 'YAML to JSON',
    description: 'Convert YAML to formatted JSON.',
    category: 'yaml',
    keywords: ['yaml', 'convert', 'json'],
    page: () => import('../pages/YamlTool').then((m) => ({ default: m.YamlTool })),
    title: 'YAML to JSON',
    descriptionMeta: 'Convert YAML to formatted JSON instantly in your browser.',
    explainTitle: 'Why convert YAML to JSON?',
    explain: null,
  },
  {
    slug: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate RFC 4122 v4 UUIDs, in bulk, with formatting options.',
    category: 'uuid',
    keywords: ['uuid', 'generator', 'id'],
    page: () => import('../pages/UuidGenerator').then((m) => ({ default: m.UuidGenerator })),
    title: 'UUID Generator',
    descriptionMeta: 'Generate RFC 4122 version 4 UUIDs in your browser. Bulk generation, uppercase and no-hyphen formatting. Nothing leaves your device.',
    explainTitle: 'What is a UUID v4?',
    explain: null,
  },
  {
    slug: 'base64',
    name: 'Base64 Encoder/Decoder',
    description: 'Encode or decode text to Base64, including the URL-safe variant.',
    category: 'encoding',
    keywords: ['base64', 'encode', 'decode'],
    page: () => import('../pages/Base64Tool').then((m) => ({ default: m.Base64Tool })),
    title: 'Base64 Encoder/Decoder',
    descriptionMeta: 'Encode or decode text to and from Base64, including URL-safe variant.',
    explainTitle: 'What is Base64?',
    explain: null,
  },
  {
    slug: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate MD5, SHA-1, SHA-256, SHA-384, and SHA-512 hashes.',
    category: 'hash',
    keywords: ['hash', 'md5', 'sha', 'generator'],
    page: () => import('../pages/HashGenerator').then((m) => ({ default: m.HashGenerator })),
    title: 'Hash Generator',
    descriptionMeta: 'Generate MD5, SHA-1, SHA-256, SHA-384, and SHA-512 hashes instantly in your browser.',
    explainTitle: 'What are cryptographic hash functions?',
    explain: null,
  },
  {
    slug: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode a JWT header and payload, with expiry status.',
    category: 'jwt',
    keywords: ['jwt', 'decode', 'header', 'payload'],
    page: () => import('../pages/JwtDecoder').then((m) => ({ default: m.JwtDecoder })),
    title: 'JWT Decoder',
    descriptionMeta: 'Decode a JWT header and payload, with expiry status and algorithm info.',
    explainTitle: 'What is a JWT?',
    explain: null,
  },
  {
    slug: 'cron-builder',
    name: 'Cron Builder',
    description: 'Build a cron expression visually, with next run times.',
    category: 'cron',
    keywords: ['cron', 'schedule', 'timer'],
    page: () => import('../pages/CronBuilder').then((m) => ({ default: m.CronBuilder })),
    title: 'Cron Builder',
    descriptionMeta: 'Build a cron expression visually and see the next run times.',
    explainTitle: 'What is a cron expression?',
    explain: null,
  },
  {
    slug: 'emi-calculator',
    name: 'EMI Calculator',
    description: 'Estimate loan payments, total interest, and amortization schedule.',
    category: 'calculator',
    keywords: ['emi', 'calculator', 'loan', 'payment'],
    page: () => import('../pages/EmiCalculator').then((m) => ({ default: m.EmiCalculator })),
    title: 'EMI Calculator',
    descriptionMeta: 'Estimate loan payments, total interest, and amortization schedule.',
    explainTitle: 'How EMI is calculated',
    explain: null,
  },
  {
    slug: 'mutual-fund-calculator',
    name: 'Mutual Fund Calculator',
    description: 'Estimate SIP and lump-sum mutual fund growth with charts.',
    category: 'calculator',
    keywords: ['mutual', 'fund', 'sip', 'calculator', 'investment'],
    page: () => import('../pages/MutualFundCalculator').then((m) => ({ default: m.MutualFundCalculator })),
    title: 'Mutual Fund Calculator',
    descriptionMeta: 'Estimate SIP and lump-sum mutual fund growth with charts.',
    explainTitle: 'How mutual fund returns are calculated',
    explain: null,
  },
  {
    slug: 'privacy',
    name: 'Privacy',
    description: 'Learn about our privacy-first approach.',
    category: 'privacy',
    keywords: ['privacy', 'browser-only'],
    page: () => import('../pages/Privacy').then((m) => ({ default: m.Privacy })),
    title: 'Privacy',
    descriptionMeta: 'Nothing you enter is ever sent to a server. All processing happens entirely in your browser.',
    explainTitle: 'Our privacy promise',
    explain: null,
  },
]